language: perl

sudo: false

perl:
    - "5.26"

env:
  - BLASTVER=2.9.0
    
addons:
    apt:
        packages:
            - gzip

install:
    - "wget http://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLASTVER}/ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "curl https://raw.githubusercontent.com/tseemann/any2fasta/master/any2fasta > bin/any2fasta"
    - "chmod +x bin/any2fasta"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-${BLASTVER}+/bin:$PATH"

script:
    - "amplikate --version"
    - "amplikate --help"
    - "blastn -version"
    - "cd perl5/Biotool && for M in *.pm ; do perl $M ; done"

